// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTRCWOdQQCvJr_Rzx77owfrzahvqdTa4',
    appId: '1:299044708960:web:3a6ae0a8e068ec9ccf9905',
    messagingSenderId: '299044708960',
    projectId: 'e-commerce-website-90ff3',
    authDomain: 'e-commerce-website-90ff3.firebaseapp.com',
    storageBucket: 'e-commerce-website-90ff3.firebasestorage.app',
    measurementId: 'G-V4NYTTYS7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ2Efs9-ypDIAfVtL2elm7hMjSroAt3zs',
    appId: '1:299044708960:android:a9a20eb8ff1554cecf9905',
    messagingSenderId: '299044708960',
    projectId: 'e-commerce-website-90ff3',
    storageBucket: 'e-commerce-website-90ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99oVYAZXkeiCg48EmceEHmn_7Z9n2V-M',
    appId: '1:299044708960:ios:2a3d36ccd95f0ed4cf9905',
    messagingSenderId: '299044708960',
    projectId: 'e-commerce-website-90ff3',
    storageBucket: 'e-commerce-website-90ff3.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99oVYAZXkeiCg48EmceEHmn_7Z9n2V-M',
    appId: '1:299044708960:ios:2a3d36ccd95f0ed4cf9905',
    messagingSenderId: '299044708960',
    projectId: 'e-commerce-website-90ff3',
    storageBucket: 'e-commerce-website-90ff3.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTRCWOdQQCvJr_Rzx77owfrzahvqdTa4',
    appId: '1:299044708960:web:dea2e3683d7d0ad8cf9905',
    messagingSenderId: '299044708960',
    projectId: 'e-commerce-website-90ff3',
    authDomain: 'e-commerce-website-90ff3.firebaseapp.com',
    storageBucket: 'e-commerce-website-90ff3.firebasestorage.app',
    measurementId: 'G-NLPBBGM1N6',
  );
}
